import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";
import Countdown from "react-countdown";

// Random component
const Completionist = () => <span>You are good to go!</span>;

// Renderer callback with condition
const renderer = ({ hours, minutes, seconds, completed }) => {
  if (completed) {
    // Render a completed state
    return <Completionist />;
  } else {
    // Render a countdown
    return (
      <span>
        {hours}:{minutes}:{seconds}
      </span>
    );
  }
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Countdown></Countdown>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Fitness Plus</a>
        </h1>
        <p>Site is UnderConstruction</p>
        <h2>
          <Countdown
            date={new Date(2023, 11, 24, 10, 33, 30, 0) + 5000}
            renderer={renderer}
          />
        </h2>
      </main>

      <footer className={styles.footer}>
        <a href="" target="_blank" rel="noopener noreferrer">
          Powered by SD09
        </a>
      </footer>
    </div>
  );
}
